### ISSUE TITLE
[FEATURE] 리덕스 툴킷 환경세팅 

### ISSUE THREAD

**Issue by Nahee-Park** [TeamYouniverse/Youniverse-Web-Release#4]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 리덕스 툴킷 초기 환경세팅

## TODO

- [ ] 폴더구조 세팅 
- [ ] slice 예시 코드 작성
