### ISSUE TITLE
 [FEATURE] 스타일 초기세팅

### ISSUE THREAD

**Issue by Nahee-Park** [TeamYouniverse/Youniverse-Web-Release#6]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 이런 걸 할거야

## TODO

- [ ] 반응형 전역 스타일 설정
- [ ] 공통적으로 사용할 색상, 폰트 theme 지정해두기
